version: '3.8'

services:
  zeus:
    build: .
    image: myftp
    cap_add:
    - NET_ADMIN
    # command: ./ftp_server 1234
    command: ./run.bash
    ports:
      - "1234:1234"
    volumes:
      - ./testdir:/code/server

  poseidon:
    build: .
    image: myftp
    # add --cap-add=NET_ADMIN
    # run $ tc qdisc add dev eth0 root netem delay 100ms loss 1%
    # command: ./ftp_client zeus 1234
    command: ./client_test.py